nameOverride: dev-lime-db

global:
  config:
    dbName: dev-lime-db
crunchy: 
  enabled: true
  postgresVersion: 17
  postGISVersion: '3.4'
  imagePullPolicy: IfNotPresent
  # Enable Standby below to create a standby cluster from the same backup location as the primary cluster.

  # enable below to start a new crunchy cluster after disaster from a backed-up location, crunchy will choose the best place to recover from.
  # follow https://access.crunchydata.com/documentation/postgres-operator/5.7/tutorials/backups-disaster-recovery/disaster-recovery
  # Clone From Backups Stored in S3
  instances:
    name: db # high availability
    replicas: 3 # 2 or 3 for high availability in TEST and PROD.
    metadata:
      annotations:
        prometheus.io/scrape: 'true' # enable prometheus scraping so you monitor the cluster in Sysdig
        prometheus.io/port: '9187'
    dataVolumeClaimSpec:
      storage: 1Gi
      storageClassName: netapp-block-standard
      walStorage: 1Gi

    requests:
      cpu: 50m
      memory: 350Mi
    limits:
      memory: 750Mi
    replicaCertCopy:
      requests:
        cpu: 1m
        memory: 32Mi
      limits:
        memory: 64Mi

  pgBackRest:
    enabled: false

    config:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        memory: 64Mi
    repoHost:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi
    sidecars:
      requests:
        cpu: 5m
        memory: 64Mi
      limits:
        memory: 128Mi
    jobs:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        memory: 256Mi

  patroni:
    postgresql:
      pg_hba:
        - "host all all 0.0.0.0/0 md5"
        - "host all all ::1/128 md5"
      parameters:
        shared_buffers: 128MB # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
        wal_buffers: "-1" # this can be set to -1 to automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
        min_wal_size: 32MB
        max_wal_size: 64MB # default is 1GB
        max_slot_wal_keep_size: 256MB # default is -1, allowing unlimited wal growth when replicas fall behind
        work_mem: 4MB # a work_mem value of 4 MB (default)
        log_min_duration_statement: 1000ms # log queries taking more than 1 second to respond.
        effective_io_concurrency: 20 #If the underlying disk can handle multiple simultaneous requests, then you should increase the effective_io_concurrency value and test what value provides the best application performance. All BCGov clusters have SSD.

  # pgBouncer values:
  proxy:
    enabled: false

  # pgMonitor values:
  pgmonitor:
    enabled: true
    exporter:
      image: # it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi

  # Use this field to set a custom password for the user that is generated with the same db name. This is important if setting up a DR site
  # that you want to have running in a read-only mode. Otherwise the dr site cannot connect to the db with the generated password till
  # it becomes the primary. I usually set it to a 24 character random password
  # If not enabled, the password will be generated randomly.
  user:
    customPassword: true # set to true or false
    password: # DO NOT UPLOAD TO GITHUB
