---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-limesurvey-php
  namespace: {{ .Values.global.licensePlate }}{{ .Values.global.sectionTag }}
  labels:
{{ include "php.labels.standard" . | indent 4 }}
data:
  php.ini: |
{{ .Files.Get "assets/php.ini" | indent 4 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: config-limesurvey-application
  namespace: {{ .Values.global.licensePlate }}{{ .Values.global.sectionTag }}
  labels:
{{ include "php.labels.standard" . | indent 4 }}
data:
  config.php: |
{{ .Files.Get "assets/config.php" | indent 4 }}