---
{{- /*
  This file is part of the LimeSurvey OpenShift deployment.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeMounts.name }}
  namespace: {{ .Values.global.licensePlate }}{{ .Values.global.sectionTag }}
  labels:
{{ include "php.labels.standard" . | indent 4 }}
spec:
  storageClassName: netapp-file-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size | quote }}
-- IGNORE ---
*/ -}}
...
