# Default values for limesurvey Helm chart (prod environment)
global:
  licensePlate: da8021
  sectionTag: -prod
  host: "deseng-limesurvey.apps.silver.devops.gov.bc.ca"

  vault:
    engine: da8021-prod
    path: "" # No specific path for production, use root
