# Default values for limesurvey Helm chart (dev environment)
global:
  licensePlate: da8021
  sectionTag: -dev
  host: "limesurvey-dev.apps.clab.devops.gov.bc.ca"
  image:
    repository: ghcr.io/uhelm/limesurvey-openshift
    tag: latest

  vault:
    engine: da8021-nonprod
    path: "/dev"
