# Default values for limesurvey Helm chart (dev environment)
global:
  licensePlate: da8021
  sectionTag: -dev
  host: "limesurvey-dev.apps.clab.devops.gov.bc.ca"

  vault:
    engine: cd77be-nonprod
    path: "/dev"
