# Default values for limesurvey Helm chart (dev environment)
global:
  licensePlate: da8021
  sectionTag: -dev
  host: "limesurvey-dev.apps.clab.devops.gov.bc.ca"
  image:
    tag: dev

  vault:
    engine: da8021-nonprod
    path: "/dev"
