# Default values for limesurvey Helm chart (test environment)
global:
  licensePlate: da8021
  sectionTag: -test
  host: "limesurvey-test.apps.clab.devops.gov.bc.ca"
  image:
    tag: test

  vault:
    engine: da8021-nonprod
    path: "/test"
