# Default values for limesurvey Helm chart (prod environment)
global:
  licensePlate: da8021
  sectionTag: -prod
  host: "limesurvey-prod.apps.clab.devops.gov.bc.ca"
  image:
    repository: ghcr.io/uhelm/limesurvey-openshift
    tag: prod

  vault:
    engine: da8021-prod
    path: "" # No specific path for production, use root
