name: Analysis

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
#  schedule:
#    - cron: "0 11 * * 0" # 3 AM PST = 12 PM UDT, runs sundays
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # https://github.com/github/codeql-action
  codeql:
    name: CodeQL
    if: (! github.event.pull_request.draft)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v4
        with:
          languages: actions
    
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:actions"

  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy:
    name: Trivy Security Scan
    if: (! github.event.pull_request.draft)
    continue-on-error: true
    permissions:
      security-events: write
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v6
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          scan-type: "fs, image"
          scanners: "vuln,secret,misconfig"
          severity: "CRITICAL,HIGH"
#          skip-dirs: '**/charts' # Skips all subchart directories

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"

  results:
    name: Results
    needs: [codeql, trivy]
    if: always() && (! failure())
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - run: echo "Success!"
