name: Helm - Deploy app to OpenShift
run-name: Helm Deployment to ${{ github.event.inputs.environment || 'dev' }} - ${{ github.event.head_commit.message || github.run_number }}
on:
  push:
    branches:
      - main
    paths:
      - "helm/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - uat
          - prod
      tag:
        description: Specify a tag to deploy; defaults to PR number
        required: false
        type: string
        

jobs:
  
  helm-deploy:
    environment: ${{ github.event.inputs.environment || 'dev' }}
    runs-on: ubuntu-latest
    steps:
       # Variables
      - if: inputs.tag  == ''
        id: pr
        uses: bcgov/action-get-pr@bfa713a9ab410c0f0c13126c35983934fc80d15b # v0.1.1
      - id: vars
        run: |
          # Vars: tag and release

          # Tag defaults to PR number, but can be overridden by inputs.tag
          tag=${{ inputs.tag || steps.pr.outputs.pr }}

          # Release name includes run numbers to ensure uniqueness
          release=${{ github.event.repository.name }}-${{ inputs.environment || steps.pr.outputs.pr || inputs.tag }}

          # version, to support helm packaging for non-pr based releases (workflow_dispatch). default to 1.0.0+github run number
          version=1.0.0+${{ github.run_number }}

            # Summary
          echo "tag=${tag}"
          echo "release=${release}"
          echo "version=${version}"

          # Output
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "release=${release}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1.13.1
        with:
          oc: "4.16"
          skip_cache: true
      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN }}
        run: |
          for i in {1..5}; do
            # Server sometimes doen't respond immediately, retry a few times
            oc login --server=$OPENSHIFT_SERVER --token=$OPENSHIFT_SA_TOKEN && break
            echo "Login failed, retrying in 5 seconds... ($i/5)"
            sleep 5
          done
      - name: Set OpenShift project
        run: |
          oc project ${{ secrets.OC_NAMESPACE }}

      - name: Update & Build Helm dependencies
        run: |
          helm dependency update ./helm
          helm dependency build ./helm
      - name: Deploy Helm chart
        run: |
          helm upgrade --install limesurvey ./helm \
            --values ./helm/values.yaml \
            --values ./helm/values-${{ github.event.inputs.environment || 'dev' }}.yaml \
            --set-string global.tag="${{ steps.vars.outputs.tag }}" \
      - name: Verify Deployment
        run: |
          oc rollout status deployment/limesurvey-nginx --timeout=180s
          oc rollout status deployment/limesurvey-php --timeout=180s
